# Generated by Django 5.0.6 on 2024-07-05 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('emergency', '紧急'), ('severe', '严重'), ('minor', '次要'), ('warning', '警告'), ('info', '信息')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('event_id', models.CharField(default='', max_length=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('unconfirmed', '未确认'), ('confirmed', '已确认')], max_length=11)),
            ],
        ),
    ]
