# Generated by Django 5.0.6 on 2024-07-05 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('emergency', '紧急'), ('severe', '严重'), ('minor', '次要'), ('warning', '警告'), ('info', '信息')], default='warning', max_length=10)),
                ('title', models.CharField(default='标题', max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='成功', max_length=10)),
            ],
        ),
    ]
